spring.application.name=rest-api
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0

# MySQL Connection to your CVUT-ver-2 database
spring.datasource.url=jdbc:mysql://localhost:3306/CVUT-ver-2?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Hibernate Table Strategy:
# "validate" verifies that your entities match your existing SQL tables without modifying them.
# "update" will adjust columns or add missing tables if you add new fields in Java.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
